# game_rules.py

class Action:
    def __init__(self, name, dice, damage_type, category="Weapon", ac=0, armor_type=None, action_type="Action", level=0, school="", scale_dice=None, classes=None, stat=None, desc=""):
        self.name = name
        self.dice = dice      
        self.type = damage_type 
        self.category = category 
        self.ac = ac
        self.armor_type = armor_type
        self.action_type = action_type 
        self.level = level
        self.school = school
        self.scale_dice = scale_dice
        self.classes = classes if classes else [] 
        self.stat = stat 
        self.desc = desc

SKILLS_LIST = {
    "Acrobatics": "DEX", "Animal Handling": "WIS", "Arcana": "INT", "Athletics": "STR", 
    "Deception": "CHA", "History": "INT", "Insight": "WIS", "Intimidation": "CHA", 
    "Investigation": "INT", "Medicine": "WIS", "Nature": "INT", "Perception": "WIS", 
    "Performance": "CHA", "Persuasion": "CHA", "Religion": "INT", "Sleight of Hand": "DEX", 
    "Stealth": "DEX", "Survival": "WIS"
}

# --- RACES ---
RACES = {
    "Human": {"bonuses": {"STR": 1, "DEX": 1, "CON": 1, "INT": 1, "WIS": 1, "CHA": 1}, "skills": [], "profs": [], "auto_spells": []},
    "High Elf": {"bonuses": {"DEX": 2, "INT": 1}, "auto_spells": ["Prestidigitation"], "skills": ["Perception"], "profs": ["Longsword", "Shortsword", "Shortbow", "Longbow"]},
    "Wood Elf": {"bonuses": {"DEX": 2, "WIS": 1}, "skills": ["Perception", "Stealth"], "profs": ["Longsword", "Shortbow"], "auto_spells": []},
    "Drow": {"bonuses": {"DEX": 2, "CHA": 1}, "skills": ["Perception"], "profs": ["Rapier", "Hand Crossbow"], "auto_spells": ["Dancing Lights"]},
    "Hill Dwarf": {"bonuses": {"CON": 2, "WIS": 1}, "hp_bonus": 1, "skills": [], "profs": ["Battleaxe", "Handaxe", "Warhammer"], "auto_spells": []},
    "Mountain Dwarf": {"bonuses": {"STR": 2, "CON": 2}, "skills": [], "profs": ["Battleaxe", "Handaxe", "Warhammer", "Light Armor", "Medium Armor"], "auto_spells": []},
    "Lightfoot Halfling": {"bonuses": {"DEX": 2, "CHA": 1}, "skills": ["Stealth"], "profs": [], "auto_spells": []},
    "Stout Halfling": {"bonuses": {"DEX": 2, "CON": 1}, "skills": [], "profs": [], "auto_spells": []},
    "Dragonborn": {"bonuses": {"STR": 2, "CHA": 1}, "skills": ["Intimidation"], "profs": [], "auto_spells": []},
    "Tiefling": {"bonuses": {"CHA": 2, "INT": 1}, "auto_spells": ["Thaumaturgy"], "skills": [], "profs": []},
    "Half-Orc": {"bonuses": {"STR": 2, "CON": 1}, "skills": ["Intimidation"], "profs": [], "auto_spells": []},
    "Gnome (Forest)": {"bonuses": {"INT": 2, "DEX": 1}, "skills": [], "profs": [], "auto_spells": ["Minor Illusion"]},
    "Gnome (Rock)": {"bonuses": {"INT": 2, "CON": 1}, "skills": [], "profs": [], "auto_spells": []},
    "Half-Elf": {"bonuses": {"CHA": 2, "DEX": 1, "CON": 1}, "skills": ["Perception", "Insight"], "profs": [], "auto_spells": []},
    "Goliath": {"bonuses": {"STR": 2, "CON": 1}, "skills": ["Athletics"], "profs": [], "auto_spells": []},
    "Firbolg": {"bonuses": {"WIS": 2, "STR": 1}, "skills": [], "profs": [], "auto_spells": ["Detect Magic", "Disguise Self"]},
    "Tabaxi": {"bonuses": {"DEX": 2, "CHA": 1}, "skills": ["Perception", "Stealth"], "profs": [], "auto_spells": []},
    "Tortle": {"bonuses": {"STR": 2, "WIS": 1}, "skills": ["Survival"], "profs": [], "auto_spells": []},
    "Warforged": {"bonuses": {"CON": 2, "STR": 1}, "skills": [], "profs": [], "auto_spells": []},
    "Aasimar": {"bonuses": {"CHA": 2}, "skills": [], "profs": [], "auto_spells": ["Light"]},
    "Genasi (Fire)": {"bonuses": {"CON": 2, "INT": 1}, "skills": [], "profs": [], "auto_spells": ["Produce Flame"]},
    "Genasi (Water)": {"bonuses": {"CON": 2, "WIS": 1}, "skills": [], "profs": [], "auto_spells": ["Shape Water"]},
}

# --- CLASSES ---
CLASSES = {
    "Artificer": {
        "hit_die": 8, "subclass_lvl": 3,
        "starting_gear": ["Light Crossbow", "Scale Mail", "Thieves' Tools"],
        "features": [(1, "Magical Tinkering"), (2, "Infuse Item")],
        "auto_spells": [(1, "Cure Wounds"), (1, "Faerie Fire")],
        "spell_rules": {"type": "Half", "prepare": "Prepared", "stat": "INT"}, 
        "saves": ["CON", "INT"],
        "skill_options": ["Arcana", "History", "Investigation", "Medicine", "Nature", "Perception", "Sleight of Hand"],
        "armor_profs": ["Light", "Medium", "Shield"], "weapon_profs": ["Simple"],
        "cantrip_progression": [2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4],
        "subclasses": {
            "Alchemist": {"features": [(3, "Experimental Elixir")]},
            "Armorer": {"features": [(3, "Arcane Armor"), (3, "Thunder Gauntlets"), (3, "Lightning Launcher")], "armor_profs": ["Heavy"]},
            "Artillerist": {"features": [(3, "Eldritch Cannon")]},
            "Battle Smith": {"features": [(3, "Steel Defender"), (3, "Battle Ready")], "weapon_profs": ["Martial"]}
        }
    },
    "Barbarian": {
        "hit_die": 12, "subclass_lvl": 3,
        "starting_gear": ["Greataxe", "Handaxe", "Javelin"],
        "features": [(1, "Rage"), (1, "Unarmored Defense"), (2, "Reckless Attack"), (5, "Extra Attack")],
        "saves": ["STR", "CON"], "skill_options": ["Animal Handling", "Athletics", "Intimidation", "Nature", "Perception", "Survival"],
        "armor_profs": ["Light", "Medium", "Shield"], "weapon_profs": ["Simple", "Martial"],
        "auto_spells": [], "spell_list": [], "spell_rules": None,
        "subclasses": {
            "Ancestral Guardian": {"features": [(3, "Ancestral Protectors")]},
            "Battlerager": {"features": [(3, "Battlerager Armor")]},
            "Beast": {"features": [(3, "Form of the Beast")]},
            "Berserker": {"features": [(3, "Frenzy (Bonus Attack)")]},
            "Storm Herald": {"features": [(3, "Storm Aura")]},
            "Totem Warrior": {"features": [(3, "Spirit Seeker"), (3, "Totem Spirit")]},
            "Wild Magic": {"features": [(3, "Wild Surge")]},
            "Zealot": {"features": [(3, "Divine Fury")]}
        }
    },
    "Bard": {
        "hit_die": 8, "subclass_lvl": 3,
        "starting_gear": ["Rapier", "Leather Armor", "Dagger"],
        "features": [(1, "Bardic Inspiration"), (2, "Jack of All Trades"), (3, "Expertise")],
        "spell_rules": {"type": "Full", "prepare": "Known", "stat": "CHA"},
        "saves": ["DEX", "CHA"], "skill_options": list(SKILLS_LIST.keys()),
        "armor_profs": ["Light"], "weapon_profs": ["Simple", "Hand Crossbow", "Longsword", "Rapier", "Shortsword"],
        "cantrip_progression": [2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        "auto_spells": [], 
        "subclasses": {
            "Creation": {"features": [(3, "Mote of Potential")]},
            "Eloquence": {"features": [(3, "Silver Tongue")]},
            "Glamour": {"features": [(3, "Mantle of Inspiration")]},
            "Lore": {"features": [(3, "Cutting Words"), (6, "Additional Magical Secrets")]},
            "Spirits": {"features": [(3, "Tales from Beyond")]},
            "Swords": {"features": [(3, "Blade Flourish")], "armor_profs": ["Medium"], "weapon_profs": ["Scimitar"]},
            "Valor": {"features": [(3, "Combat Inspiration")], "armor_profs": ["Medium", "Shield"], "weapon_profs": ["Martial"]},
            "Whispers": {"features": [(3, "Psychic Blades")]}
        }
    },
    "Cleric": {
        "hit_die": 8, "subclass_lvl": 1,
        "starting_gear": ["Mace", "Scale Mail", "Shield"],
        "features": [(2, "Channel Divinity"), (5, "Destroy Undead")],
        "spell_rules": {"type": "Full", "prepare": "Prepared", "stat": "WIS"},
        "saves": ["WIS", "CHA"], "skill_options": ["History", "Insight", "Medicine", "Persuasion", "Religion"],
        "armor_profs": ["Light", "Medium", "Shield"], "weapon_profs": ["Simple"],
        "cantrip_progression": [3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        "auto_spells": [], 
        "subclasses": {
            "Arcana": {"features": [(1, "Arcane Initiate")]},
            "Death": {"features": [(1, "Reaper")], "weapon_profs": ["Martial"]},
            "Forge": {"features": [(1, "Blessing of the Forge")], "armor_profs": ["Heavy"]},
            "Grave": {"features": [(1, "Circle of Mortality")]},
            "Knowledge": {"features": [(1, "Blessings of Knowledge")]},
            "Life": {"features": [(1, "Disciple of Life")], "auto_spells": [(1, "Bless"), (1, "Cure Wounds")], "armor_profs": ["Heavy"]},
            "Light": {"features": [(1, "Warding Flare")], "auto_spells": [(1, "Burning Hands"), (1, "Faerie Fire")]},
            "Nature": {"features": [(1, "Acolyte of Nature")], "armor_profs": ["Heavy"]},
            "Order": {"features": [(1, "Voice of Authority")], "armor_profs": ["Heavy"]},
            "Peace": {"features": [(1, "Emboldening Bond")]},
            "Tempest": {"features": [(1, "Wrath of the Storm")], "armor_profs": ["Heavy"], "weapon_profs": ["Martial"]},
            "Trickery": {"features": [(1, "Blessing of the Trickster")]},
            "Twilight": {"features": [(1, "Eyes of Night"), (1, "Vigilant Blessing")], "armor_profs": ["Heavy"], "weapon_profs": ["Martial"]},
            "War": {"features": [(1, "War Priest")], "armor_profs": ["Heavy"], "weapon_profs": ["Martial"]}
        }
    },
    "Druid": {
        "hit_die": 8, "subclass_lvl": 2,
        "starting_gear": ["Scimitar", "Leather Armor", "Shield"],
        "features": [(1, "Druidic"), (2, "Wild Shape")],
        "spell_rules": {"type": "Full", "prepare": "Prepared", "stat": "WIS"},
        "saves": ["INT", "WIS"], "skill_options": ["Arcana", "Animal Handling", "Insight", "Medicine", "Nature", "Perception", "Religion", "Survival"],
        "armor_profs": ["Light", "Medium", "Shield"], 
        "weapon_profs": ["Club", "Dagger", "Dart", "Javelin", "Mace", "Quarterstaff", "Scimitar", "Sickle", "Sling", "Spear"],
        "auto_spells": [(1, "Druidcraft")], "cantrip_progression": [2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        "subclasses": {
            "Dreams": {"features": [(2, "Balm of the Summer Court")]},
            "Land": {"features": [(2, "Natural Recovery")]},
            "Moon": {"features": [(2, "Combat Wild Shape")]},
            "Shepherd": {"features": [(2, "Spirit Totem")]},
            "Spores": {"features": [(2, "Symbiotic Entity")]},
            "Stars": {"features": [(2, "Starry Form")]},
            "Wildfire": {"features": [(2, "Summon Wildfire Spirit")]}
        }
    },
    "Fighter": {
        "hit_die": 10, "subclass_lvl": 3,
        "starting_gear": ["Chain Mail", "Longsword", "Shield"],
        "features": [(1, "Fighting Style"), (1, "Second Wind"), (2, "Action Surge"), (5, "Extra Attack")],
        "spell_rules": None,
        "saves": ["STR", "CON"], "skill_options": ["Acrobatics", "Animal Handling", "Athletics", "History", "Insight", "Intimidation", "Perception", "Survival"],
        "armor_profs": ["Light", "Medium", "Heavy", "Shield"], "weapon_profs": ["Simple", "Martial"],
        "auto_spells": [],
        "subclasses": {
            "Arcane Archer": {"features": [(3, "Arcane Shot")]},
            "Banneret": {"features": [(3, "Rallying Cry")]},
            "Battle Master": {"features": [(3, "Combat Superiority")]},
            "Cavalier": {"features": [(3, "Unwavering Mark")]},
            "Champion": {"features": [(3, "Improved Critical")]},
            "Echo Knight": {"features": [(3, "Manifest Echo")]},
            "Eldritch Knight": {"features": [(3, "Spellcasting (EK)"), (3, "Weapon Bond")], "spell_rules": {"type": "Third", "prepare": "Known", "stat": "INT"}},
            "Psi Warrior": {"features": [(3, "Psionic Power")]},
            "Rune Knight": {"features": [(3, "Rune Carver")]},
            "Samurai": {"features": [(3, "Fighting Spirit")]}
        }
    },
    "Monk": {
        "hit_die": 8, "subclass_lvl": 3,
        "starting_gear": ["Shortsword", "Dart"],
        "features": [(1, "Unarmored Defense"), (1, "Martial Arts"), (2, "Ki"), (2, "Flurry of Blows"), (5, "Stunning Strike")],
        "spell_rules": None,
        "saves": ["STR", "DEX"], "skill_options": ["Acrobatics", "Athletics", "History", "Insight", "Religion", "Stealth"],
        "armor_profs": [], "weapon_profs": ["Simple", "Shortsword"],
        "auto_spells": [],
        "subclasses": {
            "Ascendant Dragon": {"features": [(3, "Draconic Disciple")]},
            "Astral Self": {"features": [(3, "Arms of the Astral Self")]},
            "Drunken Master": {"features": [(3, "Drunken Technique")]},
            "Four Elements": {"features": [(3, "Disciple of the Elements")]},
            "Kensei": {"features": [(3, "Kensei Weapons"), (3, "Agile Parry")]},
            "Long Death": {"features": [(3, "Touch of Death")]},
            "Mercy": {"features": [(3, "Hand of Healing"), (3, "Hand of Harm")]},
            "Open Hand": {"features": [(3, "Open Hand Technique")]},
            "Shadow": {"features": [(3, "Shadow Arts")]},
            "Sun Soul": {"features": [(3, "Radiant Sun Bolt")]}
        }
    },
    "Paladin": {
        "hit_die": 10, "subclass_lvl": 3,
        "starting_gear": ["Longsword", "Shield", "Chain Mail"],
        "features": [(1, "Divine Sense"), (1, "Lay on Hands"), (2, "Divine Smite"), (5, "Extra Attack")],
        "spell_rules": {"type": "Half", "prepare": "Prepared", "stat": "CHA"},
        "saves": ["WIS", "CHA"], "skill_options": ["Athletics", "Insight", "Intimidation", "Medicine", "Persuasion", "Religion"],
        "armor_profs": ["Light", "Medium", "Heavy", "Shield"], "weapon_profs": ["Simple", "Martial"],
        "auto_spells": [], 
        "subclasses": {
            "Ancients": {"features": [(3, "Nature's Wrath")]},
            "Conquest": {"features": [(3, "Conquering Presence")]},
            "Crown": {"features": [(3, "Champion Challenge")]},
            "Devotion": {"features": [(3, "Sacred Weapon")]},
            "Glory": {"features": [(3, "Peerless Athlete")]},
            "Redemption": {"features": [(3, "Emissary of Peace")]},
            "Vengeance": {"features": [(3, "Vow of Enmity")]},
            "Watchers": {"features": [(3, "Watcher's Will")]},
            "Oathbreaker": {"features": [(3, "Control Undead")]}
        }
    },
    "Ranger": {
        "hit_die": 10, "subclass_lvl": 3,
        "starting_gear": ["Scale Mail", "Shortsword", "Longbow"],
        "features": [(1, "Favored Enemy"), (2, "Fighting Style"), (2, "Spellcasting"), (5, "Extra Attack")],
        "spell_rules": {"type": "Half", "prepare": "Known", "stat": "WIS"},
        "saves": ["STR", "DEX"], "skill_options": ["Animal Handling", "Athletics", "Insight", "Investigation", "Nature", "Perception", "Stealth", "Survival"],
        "armor_profs": ["Light", "Medium", "Shield"], "weapon_profs": ["Simple", "Martial"],
        "auto_spells": [], 
        "subclasses": {
            "Beast Master": {"features": [(3, "Ranger's Companion")]},
            "Drake Warden": {"features": [(3, "Drake Companion")]},
            "Fey Wanderer": {"features": [(3, "Dreadful Strikes")]},
            "Gloom Stalker": {"features": [(3, "Dread Ambusher")]},
            "Horizon Walker": {"features": [(3, "Planar Warrior")]},
            "Hunter": {"features": [(3, "Colossus Slayer")]},
            "Monster Slayer": {"features": [(3, "Hunter's Sense")]},
            "Swarmkeeper": {"features": [(3, "Gathered Swarm")]}
        }
    },
    "Rogue": {
        "hit_die": 8, "subclass_lvl": 3,
        "starting_gear": ["Rapier", "Shortbow", "Leather Armor"],
        "features": [(1, "Sneak Attack"), (1, "Thieves' Cant"), (2, "Cunning Action"), (5, "Uncanny Dodge")],
        "spell_rules": None,
        "saves": ["DEX", "INT"], "skill_options": ["Acrobatics", "Athletics", "Deception", "Insight", "Intimidation", "Investigation", "Perception", "Performance", "Persuasion", "Sleight of Hand", "Stealth"],
        "armor_profs": ["Light"], "weapon_profs": ["Simple", "Hand Crossbow", "Longsword", "Rapier", "Shortsword"],
        "auto_spells": [],
        "subclasses": {
            "Arcane Trickster": {"features": [(3, "Spellcasting (AT)")], "spell_rules": {"type": "Third", "prepare": "Known", "stat": "INT"}},
            "Assassin": {"features": [(3, "Assassinate")]},
            "Inquisitive": {"features": [(3, "Ear for Deceit")]},
            "Mastermind": {"features": [(3, "Master of Tactics")]},
            "Phantom": {"features": [(3, "Whispers of the Dead")]},
            "Scout": {"features": [(3, "Skirmisher")]},
            "Soulknife": {"features": [(3, "Psychic Blades")]},
            "Swashbuckler": {"features": [(3, "Fancy Footwork")]},
            "Thief": {"features": [(3, "Fast Hands")]}
        }
    },
    "Sorcerer": {
        "hit_die": 6, "subclass_lvl": 1,
        "starting_gear": ["Light Crossbow", "Dagger"],
        "features": [(1, "Spellcasting"), (2, "Font of Magic"), (2, "Convert Sorcery Points"), (3, "Metamagic")],
        "spell_rules": {"type": "Full", "prepare": "Known", "stat": "CHA"},
        "saves": ["CON", "CHA"], "skill_options": ["Arcana", "Deception", "Insight", "Intimidation", "Persuasion", "Religion"],
        "armor_profs": [], "weapon_profs": ["Dagger", "Dart", "Sling", "Quarterstaff", "Light Crossbow"],
        "cantrip_progression": [4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        "auto_spells": [], 
        "subclasses": {
            "Aberrant Mind": {"features": [(1, "Telepathic Speech")]},
            "Clockwork Soul": {"features": [(1, "Restore Balance")]},
            "Divine Soul": {"features": [(1, "Favored by the Gods")]},
            "Draconic Bloodline": {"features": [(1, "Draconic Resilience")], "hp_bonus": 1},
            "Shadow Magic": {"features": [(1, "Eyes of the Dark")]},
            "Storm Sorcery": {"features": [(1, "Tempestuous Magic")]},
            "Wild Magic": {"features": [(1, "Tides of Chaos")]}
        }
    },
    "Warlock": {
        "hit_die": 8, "subclass_lvl": 1,
        "starting_gear": ["Light Crossbow", "Leather Armor"],
        "features": [(1, "Pact Magic"), (2, "Eldritch Invocations"), (3, "Pact Boon")],
        "spell_rules": {"type": "Pact", "prepare": "Known", "stat": "CHA"},
        "saves": ["WIS", "CHA"], "skill_options": ["Arcana", "Deception", "History", "Intimidation", "Investigation", "Nature", "Religion"],
        "armor_profs": ["Light"], "weapon_profs": ["Simple"],
        "cantrip_progression": [2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        "auto_spells": [], 
        "subclasses": {
            "Archfey": {"features": [(1, "Fey Presence")]},
            "Celestial": {"features": [(1, "Healing Light")]},
            "Fathomless": {"features": [(1, "Tentacle of the Deeps")]},
            "Fiend": {"features": [(1, "Dark One's Blessing")]},
            "Genie": {"features": [(1, "Genie's Vessel")]},
            "Great Old One": {"features": [(1, "Awakened Mind")]},
            "Hexblade": {"features": [(1, "Hexblade's Curse"), (1, "Hex Warrior")], "armor_profs": ["Medium", "Shield"], "weapon_profs": ["Martial"]},
            "Undead": {"features": [(1, "Form of Dread")]},
            "Undying": {"features": [(1, "Among the Dead")]}
        }
    },
    "Wizard": {
        "hit_die": 6, "subclass_lvl": 2,
        "starting_gear": ["Dagger", "Quarterstaff"],
        "features": [(1, "Spellcasting"), (1, "Arcane Recovery")],
        "spell_rules": {"type": "Full", "prepare": "Prepared", "stat": "INT"},
        "saves": ["INT", "WIS"], "skill_options": ["Arcana", "History", "Insight", "Investigation", "Medicine", "Religion"],
        "armor_profs": [], "weapon_profs": ["Dagger", "Dart", "Sling", "Quarterstaff", "Light Crossbow"],
        "auto_spells": [(1, "Spellbook")],
        "cantrip_progression": [3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        "subclasses": {
            "Abjuration": {"features": [(2, "Arcane Ward")]},
            "Bladesinging": {"features": [(2, "Bladesong")], "armor_profs": ["Light"], "weapon_profs": ["One-handed Martial"]},
            "Chronurgy": {"features": [(2, "Chronal Shift")]},
            "Conjuration": {"features": [(2, "Minor Conjuration")]},
            "Divination": {"features": [(2, "Portent")]},
            "Enchantment": {"features": [(2, "Hypnotic Gaze")]},
            "Evocation": {"features": [(2, "Sculpt Spells")]},
            "Graviturgy": {"features": [(2, "Adjust Density")]},
            "Illusion": {"features": [(2, "Improved Minor Illusion")]},
            "Necromancy": {"features": [(2, "Grim Harvest")]},
            "Order of Scribes": {"features": [(2, "Wizardly Quill")]},
            "Transmutation": {"features": [(2, "Minor Alchemy")]},
            "War Magic": {"features": [(2, "Arcane Deflection")]}
        }
    },
}

# --- LISTS ---
# Adding generic placeholders for the new subclass features so the app doesn't crash on selection
SUBCLASS_FEATURES = [
    Action("Eldritch Cannon", "-", "Action", "Feature", action_type="Bonus Action", desc="Create a cannon that shoots force/fire or grants THP."),
    Action("Steel Defender", "-", "Pet", "Feature", action_type="Passive", desc="Construct companion. Attacks on your BA."),
    Action("Battle Ready", "INT" , "Int for Atk", "Feature", action_type="Passive", desc="Use Int for magic weapon attacks."),
    Action("Ancestral Protectors", "-", "Debuff", "Feature", action_type="Passive", desc="First creature you hit has disadvantage on attacks vs others."),
    Action("Battlerager Armor", "1d4", "Piercing", "Feature", action_type="Bonus Action", desc="Attack with spiked armor as a bonus action."),
    Action("Form of the Beast", "1d6", "Varies", "Feature", action_type="Action", desc="Gain Bite, Claws, or Tail while raging."),
    Action("Storm Aura", "2", "Damage", "Feature", action_type="Bonus Action", desc="Aura effect (Desert/Sea/Tundra) activates on Rage/BA."),
    Action("Wild Surge", "-", "Effect", "Feature", action_type="Action", desc="Random magical effect when you Rage."),
    Action("Divine Fury", "1d6+Lvl", "Necrotic", "Feature", action_type="Free", desc="First hit on turn deals extra radiant/necrotic damage."),
    Action("Mote of Potential", "-", "Buff", "Feature", action_type="Bonus Action", desc="Bardic Inspiration adds extra effects based on roll type."),
    Action("Silver Tongue", "-", "Advantage", "Feature", action_type="Passive", desc="Treat d20 roll of 9 or lower as 10 for Persuasion/Deception."),
    Action("Mantle of Inspiration", "-", "Temp HP", "Feature", action_type="Bonus Action", desc="Grant allies Temp HP and movement."),
    Action("Tales from Beyond", "-", "Random", "Feature", action_type="Bonus Action", desc="Roll on Spirit Table for effect."),
    Action("Blade Flourish", "1d6", "Damage", "Feature", action_type="Free", desc="Add Bardic Die to damage + AC/Push/Mobile."),
    Action("Psychic Blades", "2d6", "Psychic", "Feature", action_type="Free", desc="Expend Inspiration to deal psychic damage on hit."),
    Action("Arcane Initiate", "-", "Cantrip", "Feature", action_type="Passive", desc="Gain 2 Wizard cantrips."),
    Action("Reaper", "-", "Cantrip", "Feature", action_type="Passive", desc="Necromancy cantrips hit two targets if within 5ft."),
    Action("Blessing of the Forge", "1", "AC/Atk", "Feature", action_type="Action", desc="Make weapon or armor +1 until long rest."),
    Action("Circle of Mortality", "-", "Max Heal", "Feature", action_type="Passive", desc="Healing spells on 0 HP targets do max possible healing."),
    Action("Blessings of Knowledge", "-", "Skills", "Feature", action_type="Passive", desc="Proficiency and Expertise in 2 skills."),
    Action("Acolyte of Nature", "-", "Cantrip", "Feature", action_type="Passive", desc="Druid cantrip + Skill."),
    Action("Voice of Authority", "-", "Reaction", "Feature", action_type="Passive", desc="Ally you target with spell can make reaction attack."),
    Action("Emboldening Bond", "1d4", "Buff", "Feature", action_type="Action", desc="Bonded allies add d4 to attacks/saves/checks."),
    Action("Blessing of the Trickster", "-", "Stealth", "Feature", action_type="Action", desc="Grant Advantage on Stealth to another creature."),
    Action("Eyes of Night", "-", "Darkvision", "Feature", action_type="Passive", desc="300ft Darkvision, shareable."),
    Action("Vigilant Blessing", "-", "Adv Init", "Feature", action_type="Action", desc="Grant Advantage on Initiative to one creature."),
    Action("War Priest", "-", "Bonus Atk", "Feature", action_type="Bonus Action", desc="Make weapon attack as Bonus Action (Wis mod/day)."),
    Action("Balm of the Summer Court", "1d6", "Healing", "Feature", action_type="Bonus Action", desc="Pool of d6s to heal allies."),
    Action("Spirit Totem", "-", "Aura", "Feature", action_type="Bonus Action", desc="Summon spirit (Bear/Hawk/Unicorn) aura."),
    Action("Symbiotic Entity", "1d6", "Necrotic", "Feature", action_type="Action", desc="Gain Temp HP and deal extra damage while active."),
    Action("Starry Form", "-", "Transform", "Feature", action_type="Bonus Action", desc="Archer, Chalice, or Dragon form benefits."),
    Action("Summon Wildfire Spirit", "-", "Pet", "Feature", action_type="Action", desc="Summon flame spirit that shoots fire."),
    Action("Arcane Shot", "2d6", "Magical", "Feature", action_type="Free", desc="Apply magical effect to arrow (2/rest)."),
    Action("Rallying Cry", "-", "Healing", "Feature", action_type="Bonus Action", desc="Heal allies when using Second Wind."),
    Action("Unwavering Mark", "-", "Mark", "Feature", action_type="Free", desc="Mark target. Disadvantage to attack others."),
    Action("Manifest Echo", "-", "Summon", "Feature", action_type="Bonus Action", desc="Create echo. Teleport, attack from its space."),
    Action("Spellcasting (EK)", "-", "Spells", "Feature", action_type="Passive", desc="Learn Wizard spells (Abjuration/Evocation)."),
    Action("Weapon Bond", "-", "Utility", "Feature", action_type="Action", desc="Summon weapon to hand."),
    Action("Psionic Power", "1d6", "Damage/Red", "Feature", action_type="Free", desc="Psionic dice to reduce damage or add force damage."),
    Action("Rune Carver", "-", "Buff", "Feature", action_type="Action", desc="Inscribe runes on gear for passive/active effects."),
    Action("Fighting Spirit", "-", "Advantage", "Feature", action_type="Bonus Action", desc="Advantage on all attacks this turn + Temp HP."),
    Action("Draconic Disciple", "-", "Breath", "Feature", action_type="Action", desc="Breath weapon or change unarmed damage type."),
    Action("Arms of the Astral Self", "1d4", "Force", "Feature", action_type="Bonus Action", desc="Spectral arms. Reach +5ft, use Wis for Str checks."),
    Action("Drunken Technique", "-", "Speed", "Feature", action_type="Passive", desc="Flurry of Blows gives Disengage + 10ft speed."),
    Action("Disciple of the Elements", "-", "Spells", "Feature", action_type="Action", desc="Cast elemental spells with Ki."),
    Action("Kensei Weapons", "-", "Buff", "Feature", action_type="Passive", desc="Weapons count as Monk weapons. +2 AC if unarmed strike used."),
    Action("Agile Parry", "2", "AC", "Feature", action_type="Passive", desc="+2 AC if holding Kensei weapon and make unarmed strike."),
    Action("Touch of Death", "-", "Temp HP", "Feature", action_type="Passive", desc="Gain Temp HP when reducing foe to 0 HP."),
    Action("Hand of Healing", "1d4", "Healing", "Feature", action_type="Action", desc="Spend Ki to heal ally."),
    Action("Hand of Harm", "1d4", "Necrotic", "Feature", action_type="Action", desc="Spend Ki to deal extra necrotic damage."),
    Action("Radiant Sun Bolt", "1d4", "Radiant", "Feature", action_type="Action", desc="Ranged spell attack (30ft)."),
    Action("Nature's Wrath", "-", "Restrain", "Feature", action_type="Channel Divinity", desc="Vines restrain creature."),
    Action("Conquering Presence", "-", "Fear", "Feature", action_type="Channel Divinity", desc="Frighten enemies within 30ft."),
    Action("Champion Challenge", "-", "Control", "Feature", action_type="Channel Divinity", desc="Enemies cannot move more than 30ft away."),
    Action("Peerless Athlete", "-", "Advantage", "Feature", action_type="Channel Divinity", desc="Advantage on Athletics/Acrobatics. Jump distance +10ft."),
    Action("Emissary of Peace", "5", "Persuasion", "Feature", action_type="Channel Divinity", desc="+5 to Persuasion for 10 mins."),
    Action("Watcher's Will", "-", "Save Adv", "Feature", action_type="Channel Divinity", desc="Advantage on INT/WIS/CHA saves for allies."),
    Action("Control Undead", "-", "Control", "Feature", action_type="Channel Divinity", desc="Force undead to obey commands."),
    Action("Drake Companion", "-", "Pet", "Feature", action_type="Action", desc="Summon small dragon companion."),
    Action("Dreadful Strikes", "1d4", "Psychic", "Feature", action_type="Free", desc="Deal extra damage once per turn per target."),
    Action("Dread Ambusher", "1d8", "Bonus Dmg", "Feature", action_type="Passive", desc="First turn: +10 speed, extra attack deals +1d8."),
    Action("Planar Warrior", "1d8", "Force", "Feature", action_type="Bonus Action", desc="Next hit converts all damage to Force + 1d8."),
    Action("Hunter's Sense", "-", "Info", "Feature", action_type="Action", desc="Learn immunities/resistances of target."),
    Action("Gathered Swarm", "1d6", "Piercing", "Feature", action_type="Free", desc="Add damage or move self/enemy on hit."),
    Action("Spellcasting (AT)", "-", "Spells", "Feature", action_type="Passive", desc="Learn Wizard spells (Enchantment/Illusion)."),
    Action("Ear for Deceit", "-", "Min 10", "Feature", action_type="Passive", desc="Minimum roll of 8 on Insight (actually varies by table, usually reliable talent lite)."),
    Action("Master of Tactics", "-", "Help", "Feature", action_type="Bonus Action", desc="Help action as Bonus Action, range 30ft."),
    Action("Whispers of the Dead", "-", "Prof", "Feature", action_type="Passive", desc="Gain proficiency in one skill/tool on long rest."),
    Action("Skirmisher", "-", "Reaction Move", "Feature", action_type="Reaction", desc="Move half speed when enemy ends turn within 5ft."),
    Action("Fancy Footwork", "-", "Disengage", "Feature", action_type="Passive", desc="Don't provoke OA from creature you attack."),
    Action("Telepathic Speech", "-", "Comm", "Feature", action_type="Bonus Action", desc="Telepathic link with creature for minutes."),
    Action("Restore Balance", "-", "Neut Adv/Dis", "Feature", action_type="Reaction", desc="Cancel Advantage or Disadvantage on a roll."),
    Action("Favored by the Gods", "2d4", "Save Bonus", "Feature", action_type="Free", desc="Add 2d4 to failed save or attack roll (1/rest)."),
    Action("Draconic Resilience", "-", "AC 13", "Feature", action_type="Passive", desc="AC 13 + Dex. +1 HP per level."),
    Action("Eyes of the Dark", "-", "Darkvision", "Feature", action_type="Passive", desc="120ft Darkvision (magical)."),
    Action("Tempestuous Magic", "-", "Fly 10ft", "Feature", action_type="Bonus Action", desc="Fly 10ft without provoking OAs after casting lvl 1+ spell."),
    Action("Fey Presence", "-", "Charm/Fear", "Feature", action_type="Action", desc="10ft cube charm or fear."),
    Action("Healing Light", "1d6", "Healing", "Feature", action_type="Bonus Action", desc="Pool of d6s to heal range 60ft."),
    Action("Tentacle of the Deeps", "1d8", "Cold", "Feature", action_type="Bonus Action", desc="Summon tentacle that attacks and slows."),
    Action("Genie's Vessel", "-", "Storage", "Feature", action_type="Action", desc="Bottled Respite or Genies Wrath (+PB dmg)."),
    Action("Awakened Mind", "-", "Telepathy", "Feature", action_type="Passive", desc="Telepathy 30ft."),
    Action("Form of Dread", "-", "Temp HP/Fear", "Feature", action_type="Bonus Action", desc="Transform: Temp HP + Frighten on hit."),
    Action("Among the Dead", "-", "Sanctuary", "Feature", action_type="Passive", desc="Undead have to save to attack you."),
    Action("Arcane Ward", "-", "Shield HP", "Feature", action_type="Passive", desc="Ward absorbs damage."),
    Action("Bladesong", "-", "AC/Conc", "Feature", action_type="Bonus Action", desc="+Int to AC, +10 speed, Adv Acrobatics, +Int to Conc."),
    Action("Chronal Shift", "-", "Reroll", "Feature", action_type="Reaction", desc="Force reroll of attack, check, or save (2/day)."),
    Action("Minor Conjuration", "-", "Create Item", "Feature", action_type="Action", desc="Create small non-magical object."),
    Action("Portent", "-", "Dice Sub", "Feature", action_type="Free", desc="Roll 2d20 at start of day, replace any roll."),
    Action("Hypnotic Gaze", "-", "Incap", "Feature", action_type="Action", desc="Charm/Incapacitate creature within 5ft."),
    Action("Adjust Density", "-", "Speed/Weight", "Feature", action_type="Action", desc="Halve/Double weight/speed of creature."),
    Action("Improved Minor Illusion", "-", "Sound+Image", "Feature", action_type="Passive", desc="Minor Illusion creates both sound and image."),
    Action("Wizardly Quill", "-", "Scribe", "Feature", action_type="Passive", desc="Copy spells faster (2 mins/level)."),
    Action("Minor Alchemy", "-", "Transmute", "Feature", action_type="Action", desc="Change material (wood to stone, etc)."),
    Action("Arcane Deflection", "2", "AC", "Feature", action_type="Reaction", desc="+2 AC or +4 Save vs one attack."),
]

# (Include ALL_WEAPONS and ALL_SPELLS from Version 39/31 here)
# Copy pasting them to ensure completeness in your file
# --- NON-SPELL ACTIONS ---
ALL_WEAPONS = [
    Action("Unarmed Strike", "1", "Bludgeoning", "Simple Melee", stat="STR", desc="Basic melee strike."),
    Action("Dagger", "1d4", "Piercing", "Simple Melee", stat="DEX", desc="Finesse, light, thrown (20/60)."),
    Action("Handaxe", "1d6", "Slashing", "Simple Melee", stat="STR", desc="Light, thrown (20/60)."),
    Action("Javelin", "1d6", "Piercing", "Simple Melee", stat="STR", desc="Thrown (30/120)."),
    Action("Mace", "1d6", "Bludgeoning", "Simple Melee", stat="STR", desc="-"),
    Action("Quarterstaff", "1d6", "Bludgeoning", "Simple Melee", stat="STR", desc="Versatile (1d8)."),
    Action("Spear", "1d6", "Piercing", "Simple Melee", stat="STR", desc="Thrown (20/60), Versatile (1d8)."),
    Action("Light Crossbow", "1d8", "Piercing", "Simple Ranged", stat="DEX", desc="Ammo (80/320), loading, two-handed."),
    Action("Dart", "1d4", "Piercing", "Simple Ranged", stat="DEX", desc="Finesse, thrown (20/60)."),
    Action("Shortbow", "1d6", "Piercing", "Simple Ranged", stat="DEX", desc="Ammo (80/320), two-handed."),
    Action("Battleaxe", "1d8", "Slashing", "Martial Melee", stat="STR", desc="Versatile (1d10)."),
    Action("Greataxe", "1d12", "Slashing", "Martial Melee", stat="STR", desc="Heavy, two-handed."),
    Action("Greatsword", "2d6", "Slashing", "Martial Melee", stat="STR", desc="Heavy, two-handed."),
    Action("Longsword", "1d8", "Slashing", "Martial Melee", stat="STR", desc="Versatile (1d10)."),
    Action("Rapier", "1d8", "Piercing", "Martial Melee", stat="DEX", desc="Finesse."),
    Action("Scimitar", "1d6", "Slashing", "Martial Melee", stat="DEX", desc="Finesse, light."),
    Action("Shortsword", "1d6", "Piercing", "Martial Melee", stat="DEX", desc="Finesse, light."),
    Action("Warhammer", "1d8", "Bludgeoning", "Martial Melee", stat="STR", desc="Versatile (1d10)."),
    Action("Hand Crossbow", "1d6", "Piercing", "Martial Ranged", stat="DEX", desc="Ammo (30/120), light, loading."),
    Action("Longbow", "1d8", "Piercing", "Martial Ranged", stat="DEX", desc="Ammo (150/600), heavy, two-handed."),
    Action("Leather Armor", "-", "-", "Armor", 11, "Light", desc="AC 11 + Dex Modifier"),
    Action("Studded Leather", "-", "-", "Armor", 12, "Light", desc="AC 12 + Dex Modifier"),
    Action("Scale Mail", "-", "-", "Armor", 14, "Medium", desc="AC 14 + Dex (Max 2). Disadv Stealth."),
    Action("Chain Mail", "-", "-", "Armor", 16, "Heavy", desc="AC 16. Str 13 Req. Disadv Stealth."),
    Action("Plate", "-", "-", "Armor", 18, "Heavy", desc="AC 18. Str 15 Req. Disadv Stealth."),
    Action("Shield", "-", "-", "Armor", 2, "Shield", desc="+2 AC"),
    Action("Rage", "2", "Bonus Dmg", "Feature", action_type="Bonus Action", stat="STR", desc="Adv Strength checks/saves. Resist Bludg/Pierc/Slash. +2 Dmg."),
    Action("Bardic Inspiration", "1d6", "Buff", "Feature", action_type="Bonus Action", stat="CHA", desc="Grant ally 1d6 to add to ability check, attack, or save."),
    Action("Second Wind", "1d10", "Healing", "Feature", action_type="Bonus Action", stat="CON", desc="Regain 1d10 + Level HP. Once per short rest."),
    Action("Action Surge", "-", "Extra Action", "Feature", action_type="Free", desc="Take one additional action on your turn."),
    Action("Sneak Attack", "1d6", "Bonus Dmg", "Feature", action_type="Passive", scale_dice="1d6", desc="Extra damage once/turn if Adv or ally within 5ft."),
    Action("Cunning Action", "-", "Dash/Dis/Hide", "Feature", action_type="Bonus Action", desc="Bonus action to Dash, Disengage, or Hide."),
    Action("Martial Arts", "1d4", "Bludgeoning", "Feature", action_type="Bonus Action", stat="DEX", desc="Use Dex for unarmed. Bonus unarmed strike after attack."),
    Action("Ki", "-", "Resource", "Feature", action_type="Passive", desc="Spend Ki points for Flurry of Blows, Patient Defense, etc."),
    Action("Divine Smite", "2d8", "Radiant", "Feature", action_type="Free", stat="CHA", desc="Expend spell slot on hit. 2d8 + 1d8 per level above 1st."),
    Action("Lay on Hands", "-", "Heal", "Feature", action_type="Action", desc="Pool of HP (Level x 5). Touch to heal."),
    Action("Wild Shape", "-", "Transform", "Feature", action_type="Action", desc="Transform into a beast you have seen."),
    Action("Channel Divinity", "-", "Effect", "Feature", action_type="Action", desc="Magical effect based on your Domain/Oath."),
    Action("Magical Tinkering", "-", "Utility", "Feature", action_type="Action", desc="Imbue tiny object with light, audio, or message."),
    Action("Infuse Item", "-", "Enhance", "Feature", action_type="Passive", desc="Turn mundane items into magic items."),
    Action("Unarmored Defense", "-", "AC Calc", "Feature", action_type="Passive", desc="AC = 10 + Dex + Con (Barb) or Wis (Monk) when unarmored."),
    Action("Colossus Slayer", "1d8", "Bonus Dmg", "Feature", action_type="Passive", desc="Extra 1d8 damage if target is below max HP."),
    Action("Thunder Gauntlets", "1d8", "Thunder", "Weapon", action_type="Action", stat="INT", desc="Disadvantage on attacks vs others."),
    Action("Lightning Launcher", "1d6", "Lightning", "Weapon", action_type="Action", stat="INT", desc="Range 90/300. Extra 1d6 once per turn."),
]

# --- SPELLS (COMPREHENSIVE SRD LIST) ---
ALL_SPELLS = [
    Action("Acid Splash", "1d6", "Acid", "Spell", level=0, scale_dice="1d6", classes=["Sorcerer", "Wizard", "Artificer"], desc="Dex Save. Two targets within 5ft."),
    Action("Blade Ward", "-", "Resist", "Spell", level=0, classes=["Bard", "Sorcerer", "Warlock", "Wizard"], desc="Resistance to B/P/S damage until next turn."),
    Action("Chill Touch", "1d8", "Necrotic", "Spell", level=0, scale_dice="1d8", classes=["Sorcerer", "Warlock", "Wizard"], desc="Target can't heal until your next turn."),
    Action("Dancing Lights", "-", "Light", "Spell", level=0, classes=["Bard", "Sorcerer", "Wizard", "Artificer"], desc="Create 4 lights. Conc."),
    Action("Druidcraft", "-", "Utility", "Spell", level=0, classes=["Druid"], desc="Sensory effect, light fire, weather predict."),
    Action("Eldritch Blast", "1d10", "Force", "Spell", level=0, scale_dice="1d10", classes=["Warlock"], desc="120ft range. Multiple beams at higher levels."),
    Action("Fire Bolt", "1d10", "Fire", "Spell", level=0, scale_dice="1d10", classes=["Sorcerer", "Wizard", "Artificer"], desc="120ft range. Ranged spell attack."),
    Action("Guidance", "1d4", "Buff", "Spell", level=0, classes=["Cleric", "Druid", "Artificer"], desc="Add 1d4 to one ability check."),
    Action("Light", "-", "Light", "Spell", level=0, classes=["Bard", "Cleric", "Sorcerer", "Wizard", "Artificer"], desc="Object sheds light 20/20ft."),
    Action("Mage Hand", "-", "Utility", "Spell", level=0, classes=["Bard", "Sorcerer", "Warlock", "Wizard", "Artificer"], desc="Spectral hand carries 10lbs."),
    Action("Mending", "-", "Utility", "Spell", level=0, classes=["Bard", "Cleric", "Druid", "Sorcerer", "Wizard", "Artificer"], desc="Repair a single break/tear."),
    Action("Message", "-", "Comm", "Spell", level=0, classes=["Bard", "Sorcerer", "Wizard", "Artificer"], desc="Whisper message to creature 120ft."),
    Action("Minor Illusion", "-", "Illusion", "Spell", level=0, classes=["Bard", "Sorcerer", "Warlock", "Wizard"], desc="Create sound or image 5ft cube."),
    Action("Poison Spray", "1d12", "Poison", "Spell", level=0, scale_dice="1d12", classes=["Druid", "Sorcerer", "Warlock", "Wizard", "Artificer"], desc="Con Save. 10ft range."),
    Action("Prestidigitation", "-", "Utility", "Spell", level=0, classes=["Bard", "Sorcerer", "Warlock", "Wizard", "Artificer"], desc="Minor tricks, clean, warm, flavor."),
    Action("Produce Flame", "1d8", "Fire", "Spell", level=0, scale_dice="1d8", classes=["Druid"], desc="Light or throw for attack."),
    Action("Ray of Frost", "1d8", "Cold", "Spell", level=0, scale_dice="1d8", classes=["Sorcerer", "Wizard", "Artificer"], desc="Reduces speed by 10ft."),
    Action("Resistance", "1d4", "Buff", "Spell", level=0, classes=["Cleric", "Druid", "Artificer"], desc="Add 1d4 to one saving throw."),
    Action("Sacred Flame", "1d8", "Radiant", "Spell", level=0, scale_dice="1d8", classes=["Cleric"], desc="Dex Save. Ignores cover."),
    Action("Shillelagh", "1d8", "Magical", "Spell", level=0, action_type="Bonus Action", classes=["Druid"], desc="Club/Staff becomes magical d8 weapon using Wis."),
    Action("Shocking Grasp", "1d8", "Lightning", "Spell", level=0, scale_dice="1d8", classes=["Sorcerer", "Wizard", "Artificer"], desc="Touch. Adv vs Metal Armor. No reactions."),
    Action("Spare the Dying", "-", "Stabilize", "Spell", level=0, classes=["Cleric", "Artificer"], desc="Stabilize creature at 0 HP."),
    Action("Thaumaturgy", "-", "Utility", "Spell", level=0, classes=["Cleric"], desc="Loud voice, tremors, door slam."),
    Action("Thorn Whip", "1d6", "Piercing", "Spell", level=0, scale_dice="1d6", classes=["Druid", "Artificer"], desc="Pull creature 10ft closer."),
    Action("True Strike", "-", "Advantage", "Spell", level=0, classes=["Bard", "Sorcerer", "Warlock", "Wizard"], desc="Advantage on next attack next turn."),
    Action("Vicious Mockery", "1d4", "Psychic", "Spell", level=0, scale_dice="1d4", classes=["Bard"], desc="Wis Save. Disadvantage on next attack."),
    Action("Word of Radiance", "1d6", "Radiant", "Spell", level=0, scale_dice="1d6", classes=["Cleric"], desc="Con save. All enemies within 5ft."),
    Action("Thunderclap", "1d6", "Thunder", "Spell", level=0, scale_dice="1d6", classes=["Bard", "Druid", "Sorcerer", "Warlock", "Wizard"], desc="Con save. 5ft radius."),
    Action("Toll the Dead", "1d8", "Necrotic", "Spell", level=0, scale_dice="1d8", classes=["Cleric", "Warlock", "Wizard"], desc="Wis Save. d12 if damaged."),

    # Level 1
    Action("Alarm", "-", "Utility", "Spell", level=1, classes=["Ranger", "Wizard", "Artificer"], desc="Alerts when area entered. Ritual."),
    Action("Animal Friendship", "-", "Charm", "Spell", level=1, classes=["Bard", "Druid", "Ranger"], desc="Charm beast INT < 4."),
    Action("Armor of Agathys", "5", "Cold", "Spell", level=1, scale_dice="5", classes=["Warlock"], desc="Gain 5 THP. Hitters take 5 Cold dmg."),
    Action("Arms of Hadar", "2d6", "Necrotic", "Spell", level=1, scale_dice="1d6", classes=["Warlock"], desc="Str save. No reactions."),
    Action("Bane", "1d4", "Debuff", "Spell", level=1, classes=["Bard", "Cleric"], desc="Cha save. Subtract d4 from attacks/saves."),
    Action("Bless", "1d4", "Buff", "Spell", level=1, classes=["Cleric", "Paladin"], desc="Add d4 to attacks/saves. Conc."),
    Action("Burning Hands", "3d6", "Fire", "Spell", level=1, scale_dice="1d6", classes=["Sorcerer", "Wizard"], desc="15ft cone. Dex half."),
    Action("Charm Person", "-", "Charm", "Spell", level=1, classes=["Bard", "Druid", "Sorcerer", "Warlock", "Wizard"], desc="Wis save. Friendly acquaintance."),
    Action("Chromatic Orb", "3d8", "Variable", "Spell", level=1, scale_dice="1d8", classes=["Sorcerer", "Wizard"], desc="Choose Acid/Cold/Fire/Lightning/Poison/Thunder."),
    Action("Command", "-", "Control", "Spell", level=1, classes=["Cleric", "Paladin"], desc="Wis save. Flee/Drop/Halt."),
    Action("Compelled Duel", "-", "Control", "Spell", level=1, classes=["Paladin"], desc="Wis save. Disadv attacking others."),
    Action("Comprehend Languages", "-", "Utility", "Spell", level=1, classes=["Bard", "Sorcerer", "Warlock", "Wizard"], desc="Understand spoken/written."),
    Action("Create or Destroy Water", "-", "Utility", "Spell", level=1, classes=["Cleric", "Druid"], desc="10 gallons."),
    Action("Cure Wounds", "1d8", "Healing", "Spell", level=1, scale_dice="1d8", classes=["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Artificer"], desc="Touch heal + Mod."),
    Action("Detect Evil and Good", "-", "Detection", "Spell", level=1, classes=["Cleric", "Paladin"], desc="Know loc of aberration/celestial/elemental/fey/fiend/undead."),
    Action("Detect Magic", "-", "Detection", "Spell", level=1, classes=["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Sorcerer", "Wizard", "Artificer"], desc="See magical auras."),
    Action("Detect Poison and Disease", "-", "Detection", "Spell", level=1, classes=["Cleric", "Druid", "Paladin", "Ranger"], desc="Sense poison/disease."),
    Action("Disguise Self", "-", "Illusion", "Spell", level=1, classes=["Bard", "Sorcerer", "Wizard", "Artificer"], desc="Change appearance 1hr."),
    Action("Dissonant Whispers", "3d6", "Psychic", "Spell", level=1, scale_dice="1d6", classes=["Bard"], desc="Wis save. Reaction move away."),
    Action("Divine Favor", "1d4", "Radiant", "Spell", level=1, action_type="Bonus Action", classes=["Paladin"], desc="Extra damage on hits."),
    Action("Entangle", "-", "Restrain", "Spell", level=1, classes=["Druid"], desc="Str save. Difficult terrain."),
    Action("Expeditious Retreat", "-", "Dash", "Spell", level=1, action_type="Bonus Action", classes=["Sorcerer", "Warlock", "Wizard", "Artificer"], desc="Dash as BA."),
    Action("Faerie Fire", "-", "Advantage", "Spell", level=1, classes=["Bard", "Druid", "Artificer"], desc="Dex save. Adv on attacks vs target."),
    Action("False Life", "1d4", "Temp HP", "Spell", level=1, classes=["Sorcerer", "Wizard", "Artificer"], desc="Gain 1d4 + 4 THP."),
    Action("Feather Fall", "-", "Safety", "Spell", level=1, action_type="Reaction", classes=["Bard", "Sorcerer", "Wizard", "Artificer"], desc="Slow fall 5 creatures."),
    Action("Find Familiar", "-", "Summon", "Spell", level=1, classes=["Wizard"], desc="Ritual. Summon spirit animal."),
    Action("Fog Cloud", "-", "Obscurement", "Spell", level=1, classes=["Druid", "Ranger", "Sorcerer", "Wizard"], desc="Heavy obscurement."),
    Action("Goodberry", "1", "Healing", "Spell", level=1, classes=["Druid", "Ranger"], desc="10 berries, 1 HP each."),
    Action("Grease", "-", "Prone", "Spell", level=1, classes=["Wizard", "Artificer"], desc="Dex save. Prone."),
    Action("Guiding Bolt", "4d6", "Radiant", "Spell", level=1, scale_dice="1d6", classes=["Cleric"], desc="Advantage on next attack vs target."),
    Action("Healing Word", "1d4", "Healing", "Spell", level=1, action_type="Bonus Action", scale_dice="1d4", classes=["Bard", "Cleric", "Druid"], desc="Ranged BA heal."),
    Action("Hellish Rebuke", "2d10", "Fire", "Spell", level=1, action_type="Reaction", scale_dice="1d10", classes=["Warlock"], desc="Dex save half."),
    Action("Heroism", "-", "Buff", "Spell", level=1, classes=["Bard", "Paladin"], desc="Immune fear, gain THP each turn."),
    Action("Hex", "1d6", "Necrotic", "Spell", level=1, action_type="Bonus Action", classes=["Warlock"], desc="Extra dmg, Disadv on chosen ability checks."),
    Action("Hunter's Mark", "1d6", "Damage", "Spell", level=1, action_type="Bonus Action", classes=["Ranger"], desc="Extra dmg, Adv tracking."),
    Action("Identify", "-", "Info", "Spell", level=1, classes=["Bard", "Wizard", "Artificer"], desc="Learn magic properties."),
    Action("Inflict Wounds", "3d10", "Necrotic", "Spell", level=1, scale_dice="1d10", classes=["Cleric"], desc="Melee spell attack."),
    Action("Jump", "-", "Movement", "Spell", level=1, classes=["Druid", "Ranger", "Sorcerer", "Wizard", "Artificer"], desc="Triple jump distance."),
    Action("Longstrider", "-", "Speed", "Spell", level=1, classes=["Bard", "Druid", "Ranger", "Wizard", "Artificer"], desc="+10ft speed."),
    Action("Mage Armor", "-", "AC 13", "Spell", level=1, classes=["Sorcerer", "Wizard"], desc="AC becomes 13 + Dex."),
    Action("Magic Missile", "3d4", "Force", "Spell", level=1, scale_dice="1d4", classes=["Sorcerer", "Wizard"], desc="Auto-hit darts."),
    Action("Protection from Evil and Good", "-", "Buff", "Spell", level=1, classes=["Cleric", "Paladin", "Warlock", "Wizard"], desc="Disadv on attacks against you by types."),
    Action("Purify Food and Drink", "-", "Utility", "Spell", level=1, classes=["Cleric", "Druid", "Paladin", "Artificer"], desc="Remove poison/disease."),
    Action("Sanctuary", "-", "Protection", "Spell", level=1, action_type="Bonus Action", classes=["Cleric", "Artificer"], desc="Wis save to attack target."),
    Action("Shield", "-", "+5 AC", "Spell", level=1, action_type="Reaction", classes=["Sorcerer", "Wizard"], desc="+5 AC vs trigger attack."),
    Action("Shield of Faith", "-", "+2 AC", "Spell", level=1, action_type="Bonus Action", classes=["Cleric", "Paladin"], desc="+2 AC."),
    Action("Silent Image", "-", "Illusion", "Spell", level=1, classes=["Bard", "Sorcerer", "Wizard"], desc="Visual illusion."),
    Action("Sleep", "5d8", "Sleep", "Spell", level=1, scale_dice="2d8", classes=["Bard", "Sorcerer", "Wizard"], desc="Sleep by HP pool."),
    Action("Speak with Animals", "-", "Comm", "Spell", level=1, classes=["Bard", "Druid", "Ranger"], desc="Talk to beasts."),
    Action("Tasha's Hideous Laughter", "-", "Prone", "Spell", level=1, classes=["Bard", "Wizard"], desc="Wis save. Incapacitated/Prone."),
    Action("Thunderwave", "2d8", "Thunder", "Spell", level=1, scale_dice="1d8", classes=["Bard", "Druid", "Sorcerer", "Wizard"], desc="15ft cube. Con save push 10ft."),
    Action("Unseen Servant", "-", "Utility", "Spell", level=1, classes=["Bard", "Warlock", "Wizard"], desc="Invisible force performs tasks."),
    Action("Witch Bolt", "1d12", "Lightning", "Spell", level=1, scale_dice="1d12", classes=["Sorcerer", "Warlock", "Wizard"], desc="Sustained damage each turn."),

    # Level 2
    Action("Acid Arrow", "4d4", "Acid", "Spell", level=2, scale_dice="2d4", classes=["Wizard"], desc="And 2d4 next turn."),
    Action("Aid", "-", "Max HP", "Spell", level=2, classes=["Cleric", "Paladin", "Artificer"], desc="+5 Max HP to 3 targets."),
    Action("Alter Self", "-", "Buff", "Spell", level=2, classes=["Sorcerer", "Wizard", "Artificer"], desc="Change appearance or natural weapons."),
    Action("Animal Messenger", "-", "Comm", "Spell", level=2, classes=["Bard", "Druid", "Ranger"], desc="Send message via beast."),
    Action("Arcane Lock", "-", "Utility", "Spell", level=2, classes=["Wizard", "Artificer"], desc="Magically lock door."),
    Action("Augury", "-", "Divination", "Spell", level=2, classes=["Cleric"], desc="Predict future outcome."),
    Action("Barkskin", "-", "AC 16", "Spell", level=2, classes=["Druid", "Ranger"], desc="AC cannot be less than 16."),
    Action("Blindness/Deafness", "-", "Debuff", "Spell", level=2, classes=["Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"], desc="Con save."),
    Action("Blur", "-", "Defense", "Spell", level=2, classes=["Sorcerer", "Wizard", "Artificer"], desc="Disadv on attacks vs you."),
    Action("Calm Emotions", "-", "Control", "Spell", level=2, classes=["Bard", "Cleric"], desc="Suppress charm/fear."),
    Action("Cloud of Daggers", "4d4", "Slashing", "Spell", level=2, scale_dice="2d4", classes=["Bard", "Sorcerer", "Warlock", "Wizard"], desc="5ft cube area damage."),
    Action("Continual Flame", "-", "Light", "Spell", level=2, classes=["Cleric", "Wizard", "Artificer"], desc="Permanent torch."),
    Action("Darkness", "-", "Obscurement", "Spell", level=2, classes=["Sorcerer", "Warlock", "Wizard"], desc="15ft radius magical darkness."),
    Action("Darkvision", "-", "Sense", "Spell", level=2, classes=["Druid", "Ranger", "Sorcerer", "Wizard", "Artificer"], desc="60ft Darkvision."),
    Action("Detect Thoughts", "-", "Info", "Spell", level=2, classes=["Bard", "Sorcerer", "Wizard"], desc="Read surface thoughts."),
    Action("Enhance Ability", "-", "Buff", "Spell", level=2, classes=["Bard", "Cleric", "Druid", "Sorcerer", "Artificer"], desc="Advantage on checks."),
    Action("Enlarge/Reduce", "-", "Size", "Spell", level=2, classes=["Sorcerer", "Wizard", "Artificer"], desc="Size change +/- d4 dmg."),
    Action("Enthrall", "-", "Distract", "Spell", level=2, classes=["Bard", "Warlock"], desc="Distract creatures."),
    Action("Find Steed", "-", "Summon", "Spell", level=2, classes=["Paladin"], desc="Summon spirit mount."),
    Action("Find Traps", "-", "Detection", "Spell", level=2, classes=["Cleric", "Druid", "Ranger"], desc="Sense traps line of sight."),
    Action("Flame Blade", "3d6", "Fire", "Spell", level=2, scale_dice="1d6", classes=["Druid"], desc="Melee spell attack."),
    Action("Flaming Sphere", "2d6", "Fire", "Spell", level=2, scale_dice="1d6", classes=["Druid", "Wizard"], desc="Moveable ball of fire."),
    Action("Gentle Repose", "-", "Utility", "Spell", level=2, classes=["Cleric", "Wizard"], desc="Preserve corpse."),
    Action("Gust of Wind", "-", "Control", "Spell", level=2, classes=["Druid", "Sorcerer", "Wizard"], desc="Push 15ft."),
    Action("Heat Metal", "2d8", "Fire", "Spell", level=2, scale_dice="1d8", classes=["Bard", "Druid", "Artificer"], desc="Damage and Disadv if holding."),
    Action("Hold Person", "-", "Paralyze", "Spell", level=2, classes=["Bard", "Cleric", "Druid", "Sorcerer", "Warlock", "Wizard"], desc="Wis save. Humanoid only."),
    Action("Invisibility", "-", "Invisible", "Spell", level=2, classes=["Bard", "Sorcerer", "Warlock", "Wizard", "Artificer"], desc="Ends if you attack/cast."),
    Action("Knock", "-", "Unlock", "Spell", level=2, classes=["Bard", "Sorcerer", "Wizard"], desc="Open lock."),
    Action("Lesser Restoration", "-", "Cure", "Spell", level=2, classes=["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Artificer"], desc="Cure disease/condition."),
    Action("Levitate", "-", "Float", "Spell", level=2, classes=["Sorcerer", "Wizard", "Artificer"], desc="Rise 20ft."),
    Action("Locate Animals or Plants", "-", "Detection", "Spell", level=2, classes=["Bard", "Druid", "Ranger"], desc="Find specific beast/plant."),
    Action("Locate Object", "-", "Detection", "Spell", level=2, classes=["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Wizard"], desc="Find specific object."),
    Action("Magic Mouth", "-", "Utility", "Spell", level=2, classes=["Bard", "Wizard", "Artificer"], desc="Message trigger."),
    Action("Magic Weapon", "-", "Buff", "Spell", level=2, classes=["Paladin", "Wizard", "Artificer"], desc="Weapon becomes +1."),
    Action("Mirror Image", "-", "Defense", "Spell", level=2, classes=["Sorcerer", "Warlock", "Wizard"], desc="Duplicates absorb hits."),
    Action("Misty Step", "-", "Teleport", "Spell", level=2, action_type="Bonus Action", classes=["Sorcerer", "Warlock", "Wizard"], desc="30ft teleport."),
    Action("Moonbeam", "2d10", "Radiant", "Spell", level=2, scale_dice="1d10", classes=["Druid"], desc="Con save. 5ft radius."),
    Action("Pass without Trace", "-", "Stealth", "Spell", level=2, classes=["Druid", "Ranger"], desc="+10 Stealth."),
    Action("Phantasmal Force", "1d6", "Psychic", "Spell", level=2, classes=["Bard", "Sorcerer", "Wizard"], desc="Int save. Illusion damages."),
    Action("Prayer of Healing", "2d8", "Healing", "Spell", level=2, scale_dice="1d8", classes=["Cleric"], desc="10 min cast time."),
    Action("Protection from Poison", "-", "Buff", "Spell", level=2, classes=["Cleric", "Druid", "Paladin", "Ranger", "Artificer"], desc="Resist poison, cure poison."),
    Action("Ray of Enfeeblement", "-", "Debuff", "Spell", level=2, classes=["Warlock", "Wizard"], desc="Half damage str attacks."),
    Action("Rope Trick", "-", "Utility", "Spell", level=2, classes=["Wizard", "Artificer"], desc="Hiding space."),
    Action("Scorching Ray", "2d6", "Fire", "Spell", level=2, scale_dice="2d6", classes=["Sorcerer", "Wizard"], desc="3 rays."),
    Action("See Invisibility", "-", "Sense", "Spell", level=2, classes=["Bard", "Sorcerer", "Wizard"], desc="See invisible."),
    Action("Shatter", "3d8", "Thunder", "Spell", level=2, scale_dice="1d8", classes=["Bard", "Sorcerer", "Warlock", "Wizard"], desc="Con save area dmg."),
    Action("Silence", "-", "Quiet", "Spell", level=2, classes=["Bard", "Cleric", "Ranger"], desc="No sound/casting."),
    Action("Spider Climb", "-", "Movement", "Spell", level=2, classes=["Sorcerer", "Warlock", "Wizard", "Artificer"], desc="Climb walls."),
    Action("Spike Growth", "2d4", "Piercing", "Spell", level=2, classes=["Druid", "Ranger"], desc="Diff terrain, damage on move."),
    Action("Spiritual Weapon", "1d8", "Force", "Spell", level=2, action_type="Bonus Action", scale_dice="1d8", classes=["Cleric"], desc="Floating weapon attacks."),
    Action("Suggestion", "-", "Control", "Spell", level=2, classes=["Bard", "Sorcerer", "Warlock", "Wizard"], desc="Wis save. Command."),
    Action("Warding Bond", "-", "Buff", "Spell", level=2, classes=["Cleric"], desc="+1 AC/Save, split damage."),
    Action("Web", "-", "Restrain", "Spell", level=2, classes=["Sorcerer", "Wizard", "Artificer"], desc="Dex save restrain."),
    Action("Zone of Truth", "-", "Social", "Spell", level=2, classes=["Bard", "Cleric", "Paladin"], desc="Can't lie."),

    # Level 3
    Action("Animate Dead", "-", "Summon", "Spell", level=3, classes=["Cleric", "Wizard"], desc="Create zombie/skeleton."),
    Action("Aura of Vitality", "2d6", "Healing", "Spell", level=3, classes=["Paladin", "Cleric", "Druid"], desc="BA heal 2d6 per turn."),
    Action("Beacon of Hope", "-", "Buff", "Spell", level=3, classes=["Cleric"], desc="Max healing, adv wis saves."),
    Action("Bestow Curse", "-", "Debuff", "Spell", level=3, classes=["Bard", "Cleric", "Wizard"], desc="Disadv, extra dmg, or inaction."),
    Action("Blink", "-", "Defense", "Spell", level=3, classes=["Sorcerer", "Wizard"], desc="50% chance vanish."),
    Action("Call Lightning", "3d10", "Lightning", "Spell", level=3, scale_dice="1d10", classes=["Druid"], desc="Dex save area."),
    Action("Clairvoyance", "-", "Divination", "Spell", level=3, classes=["Bard", "Cleric", "Sorcerer", "Wizard"], desc="See/Hear remote location."),
    Action("Conjure Animals", "-", "Summon", "Spell", level=3, classes=["Druid", "Ranger"], desc="Summon fey beasts."),
    Action("Counterspell", "-", "Negate", "Spell", level=3, action_type="Reaction", classes=["Sorcerer", "Warlock", "Wizard"], desc="Stop spell cast."),
    Action("Create Food and Water", "-", "Utility", "Spell", level=3, classes=["Cleric", "Paladin", "Artificer"], desc="Feed 15 people."),
    Action("Daylight", "-", "Light", "Spell", level=3, classes=["Cleric", "Druid", "Paladin", "Ranger", "Sorcerer"], desc="Bright light 60ft."),
    Action("Dispel Magic", "-", "End Spell", "Spell", level=3, classes=["Bard", "Cleric", "Druid", "Paladin", "Sorcerer", "Warlock", "Wizard", "Artificer"], desc="End magical effects."),
    Action("Fear", "-", "Control", "Spell", level=3, classes=["Bard", "Sorcerer", "Warlock", "Wizard"], desc="Wis save. Frightened drop items."),
    Action("Feign Death", "-", "Utility", "Spell", level=3, classes=["Bard", "Cleric", "Druid", "Wizard"], desc="Appear dead."),
    Action("Fireball", "8d6", "Fire", "Spell", level=3, scale_dice="1d6", classes=["Sorcerer", "Wizard"], desc="Dex save. 20ft radius."),
    Action("Fly", "-", "Flight", "Spell", level=3, classes=["Sorcerer", "Warlock", "Wizard", "Artificer"], desc="60ft fly speed."),
    Action("Gaseous Form", "-", "Utility", "Spell", level=3, classes=["Sorcerer", "Warlock", "Wizard"], desc="Mist form."),
    Action("Glyph of Warding", "5d8", "Explosive", "Spell", level=3, classes=["Bard", "Cleric", "Wizard", "Artificer"], desc="Trap."),
    Action("Haste", "-", "Speed", "Spell", level=3, classes=["Sorcerer", "Wizard", "Artificer"], desc="+2 AC, double speed, extra action."),
    Action("Hunger of Hadar", "2d6", "Cold", "Spell", level=3, classes=["Warlock"], desc="Blindness, Cold/Acid dmg."),
    Action("Hypnotic Pattern", "-", "Control", "Spell", level=3, classes=["Bard", "Sorcerer", "Warlock", "Wizard"], desc="Wis save. Incapacitated."),
    Action("Lightning Bolt", "8d6", "Lightning", "Spell", level=3, scale_dice="1d6", classes=["Sorcerer", "Wizard"], desc="Dex save. Line."),
    Action("Magic Circle", "-", "Protection", "Spell", level=3, classes=["Cleric", "Paladin", "Warlock", "Wizard"], desc="Trap/block creature types."),
    Action("Major Image", "-", "Illusion", "Spell", level=3, classes=["Bard", "Sorcerer", "Warlock", "Wizard"], desc="Complex illusion."),
    Action("Mass Healing Word", "1d4", "Healing", "Spell", level=3, action_type="Bonus Action", scale_dice="1d4", classes=["Cleric"], desc="Heal 6 creatures."),
    Action("Meld into Stone", "-", "Utility", "Spell", level=3, classes=["Cleric", "Druid"], desc="Hide in stone."),
    Action("Nondetection", "-", "Utility", "Spell", level=3, classes=["Bard", "Ranger", "Wizard"], desc="Hide from divination."),
    Action("Phantom Steed", "-", "Summon", "Spell", level=3, classes=["Wizard"], desc="Fast horse."),
    Action("Plant Growth", "-", "Control", "Spell", level=3, classes=["Bard", "Druid", "Ranger"], desc="Overgrowth."),
    Action("Protection from Energy", "-", "Resist", "Spell", level=3, classes=["Cleric", "Druid", "Ranger", "Sorcerer", "Wizard", "Artificer"], desc="Resist one type."),
    Action("Remove Curse", "-", "Cure", "Spell", level=3, classes=["Cleric", "Paladin", "Warlock", "Wizard"], desc="End curse/attunement."),
    Action("Revivify", "-", "Resurrect", "Spell", level=3, classes=["Cleric", "Paladin", "Ranger", "Artificer"], desc="Revive within 1 min."),
    Action("Sending", "-", "Comm", "Spell", level=3, classes=["Bard", "Cleric", "Wizard"], desc="Message anywhere."),
    Action("Sleet Storm", "-", "Control", "Spell", level=3, classes=["Druid", "Sorcerer", "Wizard"], desc="Prone/Obscured."),
    Action("Slow", "-", "Debuff", "Spell", level=3, classes=["Sorcerer", "Wizard"], desc="No reactions, half speed."),
    Action("Speak with Dead", "-", "Info", "Spell", level=3, classes=["Bard", "Cleric"], desc="Ask 5 questions."),
    Action("Speak with Plants", "-", "Comm", "Spell", level=3, classes=["Bard", "Druid", "Ranger"], desc="Communicate/Move plants."),
    Action("Spirit Guardians", "3d8", "Radiant", "Spell", level=3, scale_dice="1d8", classes=["Cleric"], desc="Wis save. Area dmg around you."),
    Action("Stinking Cloud", "-", "Control", "Spell", level=3, classes=["Bard", "Sorcerer", "Wizard"], desc="Lose action retching."),
    Action("Tongues", "-", "Comm", "Spell", level=3, classes=["Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"], desc="Understand all languages."),
    Action("Vampiric Touch", "3d6", "Necrotic", "Spell", level=3, scale_dice="1d6", classes=["Warlock", "Wizard"], desc="Heal half dmg dealt."),
    Action("Water Breathing", "-", "Utility", "Spell", level=3, classes=["Druid", "Ranger", "Sorcerer", "Wizard", "Artificer"], desc="Breathe water 24h."),
    Action("Water Walk", "-", "Utility", "Spell", level=3, classes=["Cleric", "Druid", "Ranger", "Sorcerer", "Artificer"], desc="Walk on liquid."),
    Action("Wind Wall", "3d8", "Bludgeoning", "Spell", level=3, classes=["Druid", "Ranger"], desc="Block arrows."),

    # Level 4
    Action("Arcane Eye", "-", "Divination", "Spell", level=4, classes=["Cleric", "Wizard", "Artificer"], desc="Invisible eye scout."),
    Action("Banishment", "-", "Control", "Spell", level=4, classes=["Cleric", "Paladin", "Sorcerer", "Warlock", "Wizard"], desc="Cha save. Banish."),
    Action("Blight", "8d8", "Necrotic", "Spell", level=4, scale_dice="1d8", classes=["Druid", "Sorcerer", "Warlock", "Wizard"], desc="Con save."),
    Action("Confusion", "-", "Control", "Spell", level=4, classes=["Bard", "Druid", "Sorcerer", "Wizard"], desc="Wis save. Random acts."),
    Action("Conjure Minor Elementals", "-", "Summon", "Spell", level=4, classes=["Druid", "Wizard"], desc="Summon elementals."),
    Action("Conjure Woodland Beings", "-", "Summon", "Spell", level=4, classes=["Druid", "Ranger"], desc="Summon fey."),
    Action("Control Water", "-", "Control", "Spell", level=4, classes=["Cleric", "Druid", "Wizard"], desc="Flood/Part water."),
    Action("Death Ward", "-", "Protection", "Spell", level=4, classes=["Cleric", "Paladin"], desc="Prevent death once."),
    Action("Dimension Door", "-", "Teleport", "Spell", level=4, classes=["Bard", "Sorcerer", "Warlock", "Wizard"], desc="500ft teleport."),
    Action("Divination", "-", "Info", "Spell", level=4, classes=["Cleric", "Druid"], desc="Ask god question."),
    Action("Dominate Beast", "-", "Control", "Spell", level=4, classes=["Druid", "Sorcerer"], desc="Control animal."),
    Action("Fabricate", "-", "Creation", "Spell", level=4, classes=["Wizard", "Artificer"], desc="Create item."),
    Action("Fire Shield", "-", "Buff", "Spell", level=4, classes=["Wizard"], desc="Resist fire/cold, dmg attacker."),
    Action("Freedom of Movement", "-", "Buff", "Spell", level=4, classes=["Bard", "Cleric", "Druid", "Ranger", "Artificer"], desc="Ignore paralyze/restrain."),
    Action("Giant Insect", "-", "Transmute", "Spell", level=4, classes=["Druid"], desc="Enlarge bugs."),
    Action("Greater Invisibility", "-", "Buff", "Spell", level=4, classes=["Bard", "Sorcerer", "Wizard"], desc="Stay invisible when attacking."),
    Action("Guardian of Faith", "20", "Radiant", "Spell", level=4, classes=["Cleric"], desc="Stationary guardian."),
    Action("Hallucinatory Terrain", "-", "Illusion", "Spell", level=4, classes=["Bard", "Druid", "Warlock", "Wizard"], desc="Fake terrain."),
    Action("Ice Storm", "2d8", "Bludgeoning", "Spell", level=4, scale_dice="1d8", classes=["Druid", "Sorcerer", "Wizard"], desc="Hail + 4d6 cold."),
    Action("Locate Creature", "-", "Detection", "Spell", level=4, classes=["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Wizard"], desc="Find creature."),
    Action("Phantasmal Killer", "4d10", "Psychic", "Spell", level=4, scale_dice="1d10", classes=["Wizard"], desc="Fear dmg over time."),
    Action("Polymorph", "-", "Transform", "Spell", level=4, classes=["Bard", "Druid", "Sorcerer", "Wizard"], desc="Turn into beast."),
    Action("Private Sanctum", "-", "Utility", "Spell", level=4, classes=["Wizard"], desc="Block divination/teleport."),
    Action("Resilient Sphere", "-", "Protection", "Spell", level=4, classes=["Wizard"], desc="Invulnerable bubble."),
    Action("Secret Chest", "-", "Utility", "Spell", level=4, classes=["Wizard"], desc="Hide chest in ethereal."),
    Action("Stone Shape", "-", "Utility", "Spell", level=4, classes=["Cleric", "Druid", "Wizard", "Artificer"], desc="Reshape stone."),
    Action("Stoneskin", "-", "Resist", "Spell", level=4, classes=["Druid", "Ranger", "Sorcerer", "Wizard", "Artificer"], desc="Resist non-magic physical."),
    Action("Wall of Fire", "5d8", "Fire", "Spell", level=4, scale_dice="1d8", classes=["Druid", "Sorcerer", "Wizard"], desc="Line or ring."),

    # Level 5
    Action("Animate Objects", "1d4+4", "Bludgeoning", "Spell", level=5, classes=["Bard", "Sorcerer", "Wizard", "Artificer"], desc="Animated swarm."),
    Action("Antilife Shell", "-", "Protection", "Spell", level=5, classes=["Druid"], desc="Living can't pass."),
    Action("Awaken", "-", "Charm", "Spell", level=5, classes=["Bard", "Druid"], desc="Sentient plant/beast."),
    Action("Cloudkill", "5d8", "Poison", "Spell", level=5, scale_dice="1d8", classes=["Sorcerer", "Wizard"], desc="Moving poison fog."),
    Action("Commune", "-", "Divination", "Spell", level=5, classes=["Cleric"], desc="3 questions."),
    Action("Commune with Nature", "-", "Divination", "Spell", level=5, classes=["Druid", "Ranger"], desc="Info on surroundings."),
    Action("Cone of Cold", "8d8", "Cold", "Spell", level=5, scale_dice="1d8", classes=["Sorcerer", "Wizard"], desc="60ft cone."),
    Action("Conjure Elemental", "-", "Summon", "Spell", level=5, classes=["Druid", "Wizard"], desc="Summon elemental."),
    Action("Contact Other Plane", "-", "Divination", "Spell", level=5, classes=["Warlock", "Wizard"], desc="Int save or insane."),
    Action("Contagion", "-", "Disease", "Spell", level=5, classes=["Cleric", "Druid"], desc="Inflict disease."),
    Action("Creation", "-", "Utility", "Spell", level=5, classes=["Sorcerer", "Wizard", "Artificer"], desc="Create material object."),
    Action("Dispel Evil and Good", "-", "Protection", "Spell", level=5, classes=["Cleric", "Paladin"], desc="Banish/Protect."),
    Action("Dominate Person", "-", "Control", "Spell", level=5, classes=["Bard", "Sorcerer", "Wizard"], desc="Control humanoid."),
    Action("Dream", "-", "Comm", "Spell", level=5, classes=["Bard", "Warlock", "Wizard"], desc="Message in sleep."),
    Action("Flame Strike", "4d6", "Fire/Radiant", "Spell", level=5, scale_dice="1d6", classes=["Cleric"], desc="Cylinder fire."),
    Action("Geas", "5d10", "Psychic", "Spell", level=5, classes=["Bard", "Cleric", "Druid", "Paladin", "Wizard"], desc="Command with penalty."),
    Action("Greater Restoration", "-", "Cure", "Spell", level=5, classes=["Bard", "Cleric", "Druid", "Artificer"], desc="End charm/petrify/curse."),
    Action("Hallow", "-", "Buff", "Spell", level=5, classes=["Cleric"], desc="Consecrate ground."),
    Action("Hold Monster", "-", "Paralyze", "Spell", level=5, classes=["Bard", "Sorcerer", "Warlock", "Wizard"], desc="Paralyze any creature."),
    Action("Insect Plague", "4d10", "Piercing", "Spell", level=5, scale_dice="1d10", classes=["Cleric", "Druid", "Sorcerer"], desc="Area bugs."),
    Action("Legend Lore", "-", "Info", "Spell", level=5, classes=["Bard", "Cleric", "Wizard"], desc="Lore about item/place."),
    Action("Mass Cure Wounds", "3d8", "Healing", "Spell", level=5, scale_dice="1d8", classes=["Bard", "Cleric", "Druid"], desc="Heal 6 creatures."),
    Action("Mislead", "-", "Illusion", "Spell", level=5, classes=["Bard", "Wizard"], desc="Invisible + Duplicate."),
    Action("Modify Memory", "-", "Control", "Spell", level=5, classes=["Bard", "Wizard"], desc="Rewrite memory."),
    Action("Passwall", "-", "Utility", "Spell", level=5, classes=["Wizard"], desc="Tunnel through wall."),
    Action("Planar Binding", "-", "Control", "Spell", level=5, classes=["Bard", "Cleric", "Druid", "Wizard"], desc="Bind extraplanar."),
    Action("Raise Dead", "-", "Resurrect", "Spell", level=5, classes=["Bard", "Cleric", "Paladin"], desc="Revive within 10 days."),
    Action("Rary's Telepathic Bond", "-", "Comm", "Spell", level=5, classes=["Wizard"], desc="Group telepathy."),
    Action("Reincarnate", "-", "Resurrect", "Spell", level=5, classes=["Druid"], desc="New body."),
    Action("Scrying", "-", "Divination", "Spell", level=5, classes=["Bard", "Cleric", "Druid", "Warlock", "Wizard"], desc="Spy remote."),
    Action("Seeming", "-", "Illusion", "Spell", level=5, classes=["Bard", "Sorcerer", "Wizard"], desc="Mass disguise."),
    Action("Telekinesis", "-", "Control", "Spell", level=5, classes=["Sorcerer", "Wizard"], desc="Move objects/creatures."),
    Action("Teleportation Circle", "-", "Transport", "Spell", level=5, classes=["Bard", "Sorcerer", "Warlock", "Wizard"], desc="Teleport to circle."),
    Action("Tree Stride", "-", "Transport", "Spell", level=5, classes=["Druid", "Ranger"], desc="Step between trees."),
    Action("Wall of Force", "-", "Barrier", "Spell", level=5, classes=["Wizard"], desc="Indestructible wall."),
    Action("Wall of Stone", "-", "Barrier", "Spell", level=5, classes=["Druid", "Sorcerer", "Wizard", "Artificer"], desc="Solid wall."),

    # Level 6
    Action("Arcane Gate", "-", "Transport", "Spell", level=6, classes=["Sorcerer", "Warlock", "Wizard"], desc="Two portals."),
    Action("Blade Barrier", "6d10", "Slashing", "Spell", level=6, classes=["Cleric"], desc="Wall of blades."),
    Action("Chain Lightning", "10d8", "Lightning", "Spell", level=6, scale_dice="1d8", classes=["Sorcerer", "Wizard"], desc="Jumps to 3 targets."),
    Action("Circle of Death", "8d6", "Necrotic", "Spell", level=6, scale_dice="2d6", classes=["Sorcerer", "Warlock", "Wizard"], desc="Huge radius."),
    Action("Disintegrate", "10d6+40", "Force", "Spell", level=6, scale_dice="3d6", classes=["Sorcerer", "Wizard"], desc="Dusts target."),
    Action("Eyebite", "-", "Debuff", "Spell", level=6, classes=["Bard", "Sorcerer", "Warlock", "Wizard"], desc="Sleep/Fear/Sicken."),
    Action("Find the Path", "-", "Divination", "Spell", level=6, classes=["Bard", "Cleric", "Druid"], desc="Know way to loc."),
    Action("Flesh to Stone", "-", "Transmute", "Spell", level=6, classes=["Warlock", "Wizard"], desc="Petrify."),
    Action("Forbiddance", "-", "Protection", "Spell", level=6, classes=["Cleric"], desc="Block teleport/types."),
    Action("Globe of Invulnerability", "-", "Protection", "Spell", level=6, classes=["Sorcerer", "Wizard"], desc="Block low level spells."),
    Action("Guards and Wards", "-", "Trap", "Spell", level=6, classes=["Bard", "Wizard"], desc="Fortify area."),
    Action("Harm", "14d6", "Necrotic", "Spell", level=6, classes=["Cleric"], desc="Reduce max HP."),
    Action("Heal", "70", "Healing", "Spell", level=6, scale_dice="10", classes=["Cleric", "Druid"], desc="Heal 70, cure disease."),
    Action("Heroes' Feast", "-", "Buff", "Spell", level=6, classes=["Cleric", "Druid"], desc="Immune poison/fear, max HP."),
    Action("Instant Summons", "-", "Utility", "Spell", level=6, classes=["Wizard"], desc="Summon item."),
    Action("Irresistible Dance", "-", "Control", "Spell", level=6, classes=["Bard", "Wizard"], desc="Must dance."),
    Action("Mass Suggestion", "-", "Control", "Spell", level=6, classes=["Bard", "Sorcerer", "Warlock", "Wizard"], desc="Suggest 12 creatures."),
    Action("Move Earth", "-", "Transmute", "Spell", level=6, classes=["Druid", "Sorcerer", "Wizard"], desc="Reshape terrain."),
    Action("Planar Ally", "-", "Summon", "Spell", level=6, classes=["Cleric"], desc="Pay entity for aid."),
    Action("Programmed Illusion", "-", "Illusion", "Spell", level=6, classes=["Bard", "Wizard"], desc="Scripted illusion."),
    Action("Sunbeam", "6d8", "Radiant", "Spell", level=6, classes=["Druid", "Sorcerer", "Wizard"], desc="Line of light."),
    Action("True Seeing", "-", "Divination", "Spell", level=6, classes=["Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"], desc="See all."),
    Action("Wall of Ice", "10d6", "Cold", "Spell", level=6, classes=["Wizard"], desc="Ice wall."),
    Action("Wall of Thorns", "7d8", "Piercing", "Spell", level=6, classes=["Druid"], desc="Thorn wall."),
    Action("Wind Walk", "-", "Transport", "Spell", level=6, classes=["Druid"], desc="Turn into clouds."),
    Action("Word of Recall", "-", "Transport", "Spell", level=6, classes=["Cleric"], desc="Teleport to sanctuary."),

    # Level 7
    Action("Arcane Sword", "3d10", "Force", "Spell", level=7, classes=["Bard", "Wizard"], desc="Floating sword."),
    Action("Conjure Celestial", "-", "Summon", "Spell", level=7, classes=["Cleric"], desc="Summon celestial."),
    Action("Delayed Blast Fireball", "12d6", "Fire", "Spell", level=7, classes=["Sorcerer", "Wizard"], desc="Explodes later."),
    Action("Divine Word", "-", "Banish", "Spell", level=7, classes=["Cleric"], desc="Banish/Kill by HP."),
    Action("Etherealness", "-", "Transport", "Spell", level=7, classes=["Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"], desc="Enter Ethereal."),
    Action("Finger of Death", "7d8+30", "Necrotic", "Spell", level=7, classes=["Sorcerer", "Warlock", "Wizard"], desc="Create zombie."),
    Action("Fire Storm", "7d10", "Fire", "Spell", level=7, classes=["Cleric", "Druid", "Sorcerer"], desc="Large fire area."),
    Action("Forcecage", "-", "Trap", "Spell", level=7, classes=["Bard", "Warlock", "Wizard"], desc="Unbreakable cage."),
    Action("Mirage Arcane", "-", "Illusion", "Spell", level=7, classes=["Bard", "Druid", "Wizard"], desc="Alter terrain."),
    Action("Magnificent Mansion", "-", "Utility", "Spell", level=7, classes=["Bard", "Wizard"], desc="Safe haven."),
    Action("Plane Shift", "-", "Transport", "Spell", level=7, classes=["Cleric", "Druid", "Sorcerer", "Warlock", "Wizard"], desc="Travel planes/Banish."),
    Action("Prismatic Spray", "10d6", "Random", "Spell", level=7, classes=["Sorcerer", "Wizard"], desc="Random effects."),
    Action("Project Image", "-", "Illusion", "Spell", level=7, classes=["Bard", "Wizard"], desc="Hologram."),
    Action("Regenerate", "-", "Healing", "Spell", level=7, classes=["Bard", "Cleric", "Druid"], desc="Regrow limbs."),
    Action("Resurrection", "-", "Resurrect", "Spell", level=7, classes=["Bard", "Cleric"], desc="Revive dead."),
    Action("Reverse Gravity", "-", "Control", "Spell", level=7, classes=["Druid", "Sorcerer", "Wizard"], desc="Fall upwards."),
    Action("Sequester", "-", "Utility", "Spell", level=7, classes=["Wizard"], desc="Hide object/creature."),
    Action("Simulacrum", "-", "Duplicate", "Spell", level=7, classes=["Wizard"], desc="Snow duplicate."),
    Action("Symbol", "-", "Trap", "Spell", level=7, classes=["Bard", "Cleric", "Druid", "Wizard"], desc="Rune trap."),
    Action("Teleport", "-", "Transport", "Spell", level=7, classes=["Bard", "Sorcerer", "Wizard"], desc="Teleport anywhere."),

    # Level 8
    Action("Animal Shapes", "-", "Transform", "Spell", level=8, classes=["Druid"], desc="Mass polymorph."),
    Action("Antimagic Field", "-", "Protection", "Spell", level=8, classes=["Cleric", "Wizard"], desc="No magic zone."),
    Action("Antipathy/Sympathy", "-", "Control", "Spell", level=8, classes=["Bard", "Druid", "Wizard"], desc="Attract/Repel."),
    Action("Clone", "-", "Necromancy", "Spell", level=8, classes=["Wizard"], desc="Backup body."),
    Action("Control Weather", "-", "Utility", "Spell", level=8, classes=["Cleric", "Druid", "Wizard"], desc="Change weather."),
    Action("Demiplane", "-", "Transport", "Spell", level=8, classes=["Sorcerer", "Warlock", "Wizard"], desc="Private room."),
    Action("Dominate Monster", "-", "Control", "Spell", level=8, classes=["Bard", "Sorcerer", "Warlock", "Wizard"], desc="Control creature."),
    Action("Earthquake", "-", "Destruction", "Spell", level=8, classes=["Cleric", "Druid", "Sorcerer"], desc="Destroy structures."),
    Action("Feeblemind", "4d6", "Psychic", "Spell", level=8, classes=["Bard", "Druid", "Warlock", "Wizard"], desc="Reduce Int/Cha to 1."),
    Action("Glibness", "-", "Social", "Spell", level=8, classes=["Bard", "Warlock"], desc="Auto 15 on Cha checks."),
    Action("Holy Aura", "-", "Buff", "Spell", level=8, classes=["Cleric"], desc="Advantage and Protection."),
    Action("Incendiary Cloud", "10d8", "Fire", "Spell", level=8, classes=["Sorcerer", "Wizard"], desc="Moving fire cloud."),
    Action("Maze", "-", "Banish", "Spell", level=8, classes=["Wizard"], desc="Banish to maze."),
    Action("Mind Blank", "-", "Protection", "Spell", level=8, classes=["Bard", "Wizard"], desc="Immune psychic/divination."),
    Action("Power Word Stun", "-", "Control", "Spell", level=8, classes=["Bard", "Sorcerer", "Warlock", "Wizard"], desc="Stun if < 150HP."),
    Action("Sunburst", "12d6", "Radiant", "Spell", level=8, classes=["Druid", "Sorcerer", "Wizard"], desc="Huge radiant area."),
    Action("Telepathy", "-", "Comm", "Spell", level=8, classes=["Wizard"], desc="Unlimited range."),
    Action("Tsunami", "6d10", "Bludgeoning", "Spell", level=8, classes=["Druid"], desc="Wall of water."),

    # Level 9
    Action("Astral Projection", "-", "Transport", "Spell", level=9, classes=["Cleric", "Warlock", "Wizard"], desc="Travel astrally."),
    Action("Foresight", "-", "Buff", "Spell", level=9, classes=["Bard", "Druid", "Warlock", "Wizard"], desc="Advantage on everything."),
    Action("Gate", "-", "Transport", "Spell", level=9, classes=["Cleric", "Sorcerer", "Wizard"], desc="Portal to plane."),
    Action("Imprisonment", "-", "Control", "Spell", level=9, classes=["Warlock", "Wizard"], desc="Permanent trap."),
    Action("Mass Heal", "700", "Healing", "Spell", level=9, classes=["Cleric"], desc="700 HP pool."),
    Action("Meteor Swarm", "40d6", "Fire/Bludg", "Spell", level=9, classes=["Sorcerer", "Wizard"], desc="4 meteors."),
    Action("Power Word Heal", "-", "Healing", "Spell", level=9, classes=["Bard"], desc="Full heal."),
    Action("Power Word Kill", "100", "Instant Death", "Spell", level=9, classes=["Bard", "Sorcerer", "Warlock", "Wizard"], desc="Kill if < 100HP."),
    Action("Prismatic Wall", "-", "Barrier", "Spell", level=9, classes=["Wizard"], desc="Multi-layer wall."),
    Action("Shapechange", "-", "Transform", "Spell", level=9, classes=["Druid", "Wizard"], desc="Become any creature."),
    Action("Storm of Vengeance", "2d6", "Thunder", "Spell", level=9, classes=["Druid"], desc="Global storm."),
    Action("Time Stop", "-", "Utility", "Spell", level=9, classes=["Sorcerer", "Wizard"], desc="Take 1d4+1 turns."),
    Action("True Polymorph", "-", "Transform", "Spell", level=9, classes=["Bard", "Warlock", "Wizard"], desc="Permanent change."),
    Action("True Resurrection", "-", "Resurrect", "Spell", level=9, classes=["Cleric", "Druid"], desc="Revive anyone."),
    Action("Weird", "4d10", "Psychic", "Spell", level=9, classes=["Wizard"], desc="Mass fear/damage."),
    Action("Wish", "-", "Unlimited", "Spell", level=9, classes=["Sorcerer", "Wizard"], desc="Alter reality."),
]

ALL_ACTIONS = ALL_WEAPONS + ALL_SPELLS + SUBCLASS_FEATURES